query launches($sort: String = "date", $order: SortOrder = desc, $limit: Int = 10) {
  launches(sort: $sort, order: $order, filter: { name: "Starlink" }, limit: $limit) {
    id
    details
    name
    date
    success
    links {
      article
      patch {
        small
      }
    }
    rocket {
      name
      type
    }
  }
}
